services:

  postgres:
    image: postgres:16.1
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "./data:/var/lib/postgresql/data"